# Generated by Django 3.2.9 on 2021-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Puissance_modulaire_kW', models.SmallIntegerField()),
                ('Surface_Panneau_m2', models.SmallIntegerField()),
                ('Puissance_ondulaire_batterie_kW', models.SmallIntegerField()),
            ],
        ),
    ]
