# Generated by Django 3.2.9 on 2021-11-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='Puissance_modulaire_kW',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modules',
            name='Puissance_ondulaire_batterie_kW',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modules',
            name='Surface_Panneau_m2',
            field=models.FloatField(),
        ),
    ]
