# Generated by Django 3.2.9 on 2021-11-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0002_auto_20211126_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='ModulesPV',
        ),
    ]
