# Generated by Django 3.2.9 on 2021-11-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0003_rename_modules_modulespv'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.PositiveIntegerField(unique=True)),
                ('Onduleur_1', models.CharField(max_length=100)),
                ('Batterie_1', models.CharField(blank=True, max_length=100)),
                ('Nombre_Batterie_1', models.PositiveIntegerField(blank=True)),
                ('Onduleur_2', models.CharField(blank=True, max_length=100)),
                ('Batterie_2', models.CharField(blank=True, max_length=100)),
                ('Nombre_Batterie_2', models.PositiveIntegerField(blank=True)),
                ('Onduleur_3', models.CharField(blank=True, max_length=100)),
                ('Module_batterie_1', models.CharField(blank=True, max_length=100)),
                ('Module_batterie_2', models.CharField(blank=True, max_length=100)),
                ('Electrical_installation', models.CharField(max_length=100)),
                ('Nb_modules_min', models.PositiveIntegerField()),
                ('Puissance_centrale_max', models.FloatField()),
                ('Capacit_batterie', models.FloatField()),
                ('Prix_total_achat', models.PositiveIntegerField()),
            ],
        ),
    ]
