# Generated by Django 3.2.9 on 2021-12-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0004_bdd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_batiment', models.CharField(choices=[('AG', 'Agriculture'), ('AB', 'Activités de bureaux'), ('GA', 'Grande distribution alimentaire'), ('PMA', 'Petit et moyen commerce alimentaire'), ('CNA', 'Commerce non alimentaire'), ('MB', 'Métiers de bouche'), ('CHR', 'Cafés Hôtels Restaurants'), ('I', 'Industrie'), ('BTP', 'BTP'), ('CBE', 'Coiffeur, beauté, esthéticienne'), ('M', 'Mécanique automobile, 2 roues, vélo'), ('S', 'Santé(Clinique, laboratoire, pharmacie)'), ('AB', 'Agences bancaires'), ('T', 'Telecom(Data Center)'), ('A', 'Autre')], max_length=255, verbose_name='Type de Bâtiment')),
                ('nb_batiment', models.PositiveIntegerField(verbose_name='Nombre de bâtiments de ce type')),
                ('surface', models.PositiveIntegerField(verbose_name='Surface de toiture')),
                ('taille', models.CharField(choices=[('Petit', 'Petit (< 150m²)'), ('Moyen', 'Moyen (150-500m²)'), ('Grand', 'Grand (500m²-1000m²)'), ('Tres grand', 'Très grand (> 1000m²)')], max_length=255, verbose_name='Taille')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255, verbose_name='Nom Entreprise')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='EDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puissance', models.PositiveIntegerField(verbose_name='Puissance souscrite')),
                ('reference', models.CharField(choices=[('Mensuelle', 'Mensuelle '), ('Bimestrielle', 'Bimestrielle '), ('Annuelle', 'Annuelle ')], max_length=255, verbose_name='Reference')),
                ('nb_kW', models.PositiveIntegerField(verbose_name='Nombre KWh facture')),
                ('facture', models.PositiveIntegerField(verbose_name='Montant facture ')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PV.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territ', models.CharField(max_length=255, verbose_name='Territoire')),
            ],
        ),
        migrations.CreateModel(
            name='Toiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toiture', models.CharField(choices=[('Tôle', 'Tôle'), ('Tôle bac acier trapézoïdal', 'Tôle bac acier trapézoïdal')], max_length=255, verbose_name='Toiture')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PV.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_profil', models.CharField(choices=[('tertiaire', 'Tertiaire'), ('hotel', 'Hôtel'), ('particulier', 'Particulier'), ('fast_food', 'Fast Food'), ('station', 'Station')], max_length=255, verbose_name='Profil')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PV.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur', models.CharField(max_length=255, verbose_name='Secteur')),
                ('nb_sites', models.PositiveIntegerField(verbose_name='Nombre de sites')),
                ('effectif', models.PositiveIntegerField(verbose_name='Effectif')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PV.client')),
            ],
        ),
        migrations.CreateModel(
            name='Electrification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation', models.CharField(choices=[(1, 'Monophasée'), (0, 'Triphasée')], max_length=255, verbose_name='Installation')),
                ('souscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PV.edf')),
            ],
        ),
        migrations.AddField(
            model_name='batiment',
            name='enseigne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PV.enseigne'),
        ),
    ]
