# Generated by Django 3.2.9 on 2021-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0005_auto_20211203_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batiment',
            name='surface',
        ),
        migrations.AddField(
            model_name='toiture',
            name='surface',
            field=models.PositiveIntegerField(default=0, verbose_name='Surface de toiture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electrification',
            name='installation',
            field=models.CharField(choices=[('Monophasée', 'Monophasée'), ('Triphasée', 'Triphasée')], max_length=255, verbose_name='Installation'),
        ),
    ]
