# Generated by Django 3.2.9 on 2021-12-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0006_auto_20211206_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='batiment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PV.batiment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batiment',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='edf',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
