# Generated by Django 3.2.9 on 2021-12-06 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0007_auto_20211206_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='enseigne',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PV.enseigne'),
        ),
        migrations.AlterField(
            model_name='edf',
            name='batiment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PV.batiment'),
        ),
        migrations.AlterField(
            model_name='electrification',
            name='souscription',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PV.edf'),
        ),
        migrations.AlterField(
            model_name='enseigne',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PV.client'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='batiment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PV.batiment'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='batiment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PV.batiment'),
        ),
        migrations.AlterField(
            model_name='toiture',
            name='batiment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PV.batiment'),
        ),
    ]
