# Generated by Django 3.2.9 on 2021-12-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0008_auto_20211206_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigne',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
