# Generated by Django 3.2.9 on 2021-12-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0009_alter_enseigne_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='edf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edf_batiment', to='PV.edf'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Localisation_batiment', to='PV.localisation'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profil_batiment', to='PV.profil'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='toiture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Toiture_batiment', to='PV.toiture'),
        ),
        migrations.AddField(
            model_name='client',
            name='enseigne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enseigne_client', to='PV.enseigne'),
        ),
        migrations.AddField(
            model_name='edf',
            name='electrification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='souscription_batiment', to='PV.electrification'),
        ),
        migrations.AddField(
            model_name='enseigne',
            name='batiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Batiment_id_client', to='PV.batiment'),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='enseigne',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enseigne_batiment', to='PV.enseigne'),
        ),
        migrations.AlterField(
            model_name='edf',
            name='batiment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiment_edf', to='PV.batiment'),
        ),
        migrations.AlterField(
            model_name='electrification',
            name='souscription',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiment_souscription', to='PV.edf'),
        ),
        migrations.AlterField(
            model_name='enseigne',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client_Enseigne', to='PV.client'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='batiment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Batiment_localisation', to='PV.batiment'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='batiment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiment_profil', to='PV.batiment'),
        ),
        migrations.AlterField(
            model_name='toiture',
            name='batiment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiment_toiture', to='PV.batiment'),
        ),
    ]
