# Generated by Django 3.2.9 on 2021-12-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0011_alter_profil_type_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='Batterie_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Batterie_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Capacit_batterie',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Electrical_installation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Module_batterie_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Module_batterie_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='N',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Nb_modules_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Nombre_Batterie_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Nombre_Batterie_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Onduleur_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Onduleur_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Onduleur_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Prix_total_achat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='Puissance_centrale_max',
            field=models.FloatField(null=True),
        ),
    ]
