# Generated by Django 3.2.9 on 2021-12-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0012_auto_20211208_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules_factu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('qt', models.PositiveIntegerField(verbose_name='Quantité')),
                ('cout_unitaire', models.PositiveIntegerField(verbose_name='Coût HA unitaire')),
                ('cout_unitaire_transport', models.PositiveIntegerField(blank=True, verbose_name='Coût Unitaire Transport')),
                ('predef', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix unitaire prédéfini ')),
                ('cout_total', models.PositiveIntegerField(verbose_name='Coût Total HA')),
                ('cout_total_transport', models.PositiveIntegerField(blank=True, verbose_name='Coût Total Transport')),
                ('marge', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
                ('prix_unitaire', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territ', models.CharField(max_length=100)),
                ('transport_1', models.FloatField(verbose_name='Main doeuvre en %')),
                ('transport_2', models.FloatField(verbose_name='Panneaux en %')),
                ('transport_3', models.FloatField(verbose_name='Le reste en %')),
                ('Pose_PV_toiture_tole', models.FloatField(verbose_name='Raccordement < 50kWc')),
                ('Pose_PV_toiture_tole_2', models.FloatField(verbose_name=' Raccordement > 50kWc')),
                ('Pose_PV_toiture_terrasse', models.FloatField(verbose_name='Raccordement < 50kWc')),
                ('Pose_PV_toiture_terrasse_2', models.FloatField(verbose_name=' Raccordement > 50kWc')),
                ('Pose_PV_toiture_tuile', models.FloatField(verbose_name='Raccordement < 10kWc')),
                ('Pose_PV_toiture_tuile_2', models.FloatField(verbose_name='Raccordement < 50kWc')),
                ('Pose_PV_toiture_tole_3', models.FloatField(verbose_name=' Raccordement > 50kWc')),
                ('pose', models.FloatField(verbose_name=' Pose plot soprasolar ')),
                ('install', models.FloatField(verbose_name=' Installation et mise en service borne')),
                ('tva_entreprise', models.FloatField()),
                ('tva_particulier', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='modulespv',
            name='Cout',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='type_batiment',
            field=models.CharField(choices=[('AG', 'Agriculture'), ('ADB', 'Activités de bureaux'), ('GA', 'Grande distribution alimentaire'), ('PMA', 'Petit et moyen commerce alimentaire'), ('CNA', 'Commerce non alimentaire'), ('MB', 'Métiers de bouche'), ('CHR', 'Cafés Hôtels Restaurants'), ('I', 'Industrie'), ('BTP', 'BTP'), ('CBE', 'Coiffeur, beauté, esthéticienne'), ('M', 'Mécanique automobile, 2 roues, vélo'), ('S', 'Santé(Clinique, laboratoire, pharmacie)'), ('AB', 'Agences bancaires'), ('T', 'Telecom(Data Center)'), ('A', 'Autre')], max_length=255, verbose_name='Type de Bâtiment'),
        ),
    ]
