# Generated by Django 3.2.9 on 2021-12-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0013_auto_20211220_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxes',
            new_name='Taxe',
        ),
    ]
