# Generated by Django 3.2.9 on 2021-12-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0014_rename_taxes_taxe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxe',
            name='Pose_PV_toiture_terrasse',
            field=models.FloatField(verbose_name='Pose PV toiture Terrasse + Raccordement < 50kWc'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='Pose_PV_toiture_terrasse_2',
            field=models.FloatField(verbose_name=' Pose PV toiture Terrasse + Raccordement > 50kWc'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='Pose_PV_toiture_tole',
            field=models.FloatField(verbose_name=' Pose PV toiture tôle + Raccordement < 50kWc'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='Pose_PV_toiture_tole_2',
            field=models.FloatField(verbose_name='Pose PV toiture tôle + Raccordement > 50kWc'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='Pose_PV_toiture_tole_3',
            field=models.FloatField(verbose_name='  Pose PV toiture Tuiles +Raccordement > 50kWc'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='Pose_PV_toiture_tuile',
            field=models.FloatField(verbose_name=' Pose PV toiture Tuiles +Raccordement < 10kWc'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='Pose_PV_toiture_tuile_2',
            field=models.FloatField(verbose_name=' Pose PV toiture Tuiles +Raccordement < 50kWc'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='territ',
            field=models.CharField(max_length=100, verbose_name='Territoire'),
        ),
    ]
