# Generated by Django 3.2.9 on 2021-12-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0015_auto_20211220_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('nom_francais', models.CharField(blank=True, max_length=100)),
                ('nom_anglais', models.CharField(blank=True, max_length=100)),
                ('cout', models.FloatField(verbose_name='Coût dachat + installation en €/ml')),
            ],
        ),
        migrations.CreateModel(
            name='Cheminement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('nom_francais', models.CharField(blank=True, max_length=100)),
                ('nom_anglais', models.CharField(blank=True, max_length=100)),
                ('cout', models.FloatField(verbose_name='Coût dachat + installation en €/ml')),
            ],
        ),
        migrations.CreateModel(
            name='Divers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('nom_francais', models.CharField(blank=True, max_length=100)),
                ('nom_anglais', models.CharField(blank=True, max_length=100)),
                ('cout', models.FloatField(verbose_name='Coût dachat')),
            ],
        ),
        migrations.CreateModel(
            name='Inge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('nom_francais', models.CharField(blank=True, max_length=100)),
                ('nom_anglais', models.CharField(blank=True, max_length=100)),
                ('cout', models.FloatField(verbose_name='Coût dachat en €')),
            ],
        ),
        migrations.CreateModel(
            name='Main_doeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('nom_francais', models.CharField(blank=True, max_length=100)),
                ('nom_anglais', models.CharField(blank=True, max_length=100)),
                ('cout', models.FloatField(verbose_name='Coût dachat')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('nom_francais', models.CharField(blank=True, max_length=100)),
                ('nom_anglais', models.CharField(blank=True, max_length=100)),
                ('cout', models.FloatField(verbose_name='Coût dachat')),
                ('puissance_max', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Onduleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('nom_francais', models.CharField(blank=True, max_length=100)),
                ('nom_anglais', models.CharField(blank=True, max_length=100)),
                ('cout', models.FloatField(verbose_name='Coût dachat')),
                ('install', models.CharField(max_length=100, verbose_name='Installation  éléctrique')),
                ('tension', models.FloatField(blank=True, verbose_name='Tension DC min')),
                ('puissance_dc', models.FloatField(verbose_name='Puissance DC max en kWc')),
                ('puissance_ac', models.FloatField(verbose_name='Puissance AC max en kWc')),
            ],
        ),
        migrations.CreateModel(
            name='Tableaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('nom_francais', models.CharField(blank=True, max_length=100)),
                ('nom_anglais', models.CharField(blank=True, max_length=100)),
                ('cout', models.FloatField(verbose_name='Coût dachat')),
            ],
        ),
    ]
