# Generated by Django 3.2.9 on 2021-12-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0016_cables_cheminement_divers_inge_main_doeuvre_monitoring_onduleurs_tableaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='puissance_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
