# Generated by Django 3.2.9 on 2021-12-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0017_alter_monitoring_puissance_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onduleurs',
            name='tension',
            field=models.FloatField(blank=True, null=True, verbose_name='Tension DC min'),
        ),
    ]
