# Generated by Django 3.2.9 on 2021-12-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0018_alter_onduleurs_tension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('nom_francais', models.CharField(blank=True, max_length=100)),
                ('nom_anglais', models.CharField(blank=True, max_length=100)),
                ('cout', models.FloatField(verbose_name='Coût dachat en €/Wc')),
            ],
        ),
        migrations.AlterField(
            model_name='toiture',
            name='toiture',
            field=models.CharField(choices=[('Terrasse', 'Terrasse'), ('Tôle bac acier trapézoïdal', 'Tôle bac acier trapézoïdal')], max_length=255, verbose_name='Toiture'),
        ),
    ]
