# Generated by Django 3.2.9 on 2021-12-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0019_auto_20211220_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules_factu',
            name='batiment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batiment_factu', to='PV.batiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules_factu',
            name='client',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Client_factu', to='PV.client'),
            preserve_default=False,
        ),
    ]
