# Generated by Django 3.2.9 on 2022-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0021_auto_20220103_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDDBat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name="Secteurs d'activité proposés par SEIZE (utilisé)")),
                ('moy_kWh_avant', models.PositiveIntegerField(verbose_name='Moyenne par Secteur (kWh/an/m²) AVANT AUDIT ')),
                ('moy_kWh_apres', models.PositiveIntegerField(verbose_name='Moyenne par Secteur (kWh/an/m²) APRES AUDIT')),
                ('moy_euros_avant', models.PositiveIntegerField(verbose_name='Moyenne par Secteur (€/an/m²) AVANT AUDIT ')),
                ('moy_euros_apres', models.PositiveIntegerField(verbose_name='Moyenne par Secteur (€/an/m²) APRES AUDIT')),
                ('cout_kWh_avant', models.PositiveIntegerField(verbose_name='Coût du kWh moyen avant audit')),
                ('cout_kWh_apres', models.PositiveIntegerField(verbose_name='Coût du kWh moyen après audit')),
                ('gain', models.PositiveIntegerField(verbose_name='Gain atteingable dans le secteur')),
            ],
        ),
    ]
