# Generated by Django 3.2.9 on 2022-01-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0023_auto_20220104_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bddbat',
            name='cout_kWh_apres',
            field=models.FloatField(blank=True, null=True, verbose_name='Coût du kWh moyen après audit'),
        ),
        migrations.AlterField(
            model_name='bddbat',
            name='cout_kWh_avant',
            field=models.FloatField(verbose_name='Coût du kWh moyen avant audit'),
        ),
        migrations.AlterField(
            model_name='bddbat',
            name='gain',
            field=models.FloatField(blank=True, null=True, verbose_name='Gain atteingable dans le secteur'),
        ),
        migrations.AlterField(
            model_name='bddbat',
            name='moy_euros_apres',
            field=models.FloatField(verbose_name='Moyenne par Secteur (€/an/m²) APRES AUDIT'),
        ),
        migrations.AlterField(
            model_name='bddbat',
            name='moy_euros_avant',
            field=models.FloatField(verbose_name='Moyenne par Secteur (€/an/m²) AVANT AUDIT '),
        ),
        migrations.AlterField(
            model_name='bddbat',
            name='moy_kWh_apres',
            field=models.FloatField(verbose_name='Moyenne par Secteur (kWh/an/m²) APRES AUDIT'),
        ),
        migrations.AlterField(
            model_name='bddbat',
            name='moy_kWh_avant',
            field=models.FloatField(verbose_name='Moyenne par Secteur (kWh/an/m²) AVANT AUDIT '),
        ),
        migrations.AlterField(
            model_name='emisission_co2',
            name='emission',
            field=models.FloatField(verbose_name='Hypothèses Emissions CO2 en kg CO2/kWh\t'),
        ),
        migrations.AlterField(
            model_name='emisission_co2',
            name='territ',
            field=models.CharField(max_length=100, verbose_name='Territoire'),
        ),
        migrations.AlterField(
            model_name='ez_drive',
            name='invest',
            field=models.FloatField(blank=True, null=True, verbose_name='Investissement initial en €'),
        ),
        migrations.AlterField(
            model_name='ez_drive',
            name='valeur',
            field=models.FloatField(verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='hyp_cout_mobilite',
            name='valeur',
            field=models.FloatField(verbose_name='Valeur'),
        ),
    ]
