# Generated by Django 3.2.9 on 2022-01-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0024_auto_20220104_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='nb_etages',
            field=models.PositiveIntegerField(default=1, verbose_name="Nombre d'étage"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batiment',
            name='type_batiment',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Activités de bureaux', 'Activités de bureaux'), ('Grande distribution alimentaire', 'Grande distribution alimentaire'), ('Petit et moyen commerce alimentaire', 'Petit et moyen commerce alimentaire'), ('Commerce non alimentaire', 'Commerce non alimentaire'), ('Métiers de bouche', 'Métiers de bouche'), ('Cafés Hôtels Restaurants', 'Cafés Hôtels Restaurants'), ('Industrie', 'Industrie'), ('BTP', 'BTP'), ('Coiffeur, beauté, esthéticienne', 'Coiffeur, beauté, esthéticienne'), ('Mécanique automobile, 2 roues, vélo', 'Mécanique automobile, 2 roues, vélo'), ('Santé(Clinique, laboratoire, pharmacie)', 'Santé(Clinique, laboratoire, pharmacie)'), ('Agences bancaires', 'Agences bancaires'), ('Telecom(Data Center)', 'Telecom(Data Center)'), ('Autre', 'Autre')], max_length=255, verbose_name='Type de Bâtiment'),
        ),
    ]
