# Generated by Django 3.2.9 on 2022-01-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0025_auto_20220104_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicule_fonction', models.PositiveIntegerField(verbose_name='Nombre de véhicules de fonction')),
                ('km_an_vehicule_fonction', models.PositiveIntegerField(verbose_name='Nombre de km/an véhicule de fonction')),
                ('vehicule_utilitaire', models.PositiveIntegerField(verbose_name='Nombre de véhicules utilitaires')),
                ('km_an_vehicule_utilitaire', models.PositiveIntegerField(verbose_name='Nombre de km/an véhicule utilitaires')),
                ('parking', models.CharField(choices=[('Oui', 'Oui '), ('Non', 'Non ')], max_length=255, verbose_name='Présence parking ')),
                ('acces', models.CharField(choices=[('Public', 'Public '), ('Privé', 'Privé ')], max_length=255, verbose_name='Accessibilité Parking')),
                ('borne', models.CharField(choices=[('Oui', 'Oui '), ('Non', 'Non ')], max_length=255, verbose_name='Option Borne')),
                ('pt_de_charge', models.PositiveIntegerField(verbose_name='Nombre de point de charges desirés')),
                ('mobilite', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiment_mobilite', to='PV.batiment')),
            ],
        ),
    ]
