# Generated by Django 3.2.9 on 2022-01-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0026_mobilite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilite',
            old_name='mobilite',
            new_name='batiment',
        ),
    ]
